# Generated by Django 3.0.10 on 2020-09-15 06:26

from django.db import migrations, models
import fileManagement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('file_path', models.FileField(storage=fileManagement.models.MyStorage(), upload_to=fileManagement.models.upload_to, verbose_name='文件')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
